-- Seed 30 tasks do backlogu projektu 26 (testovací projekt)
-- Spusti v PostgreSQL: psql -U <user> -d <database> -f seed_tasks_project_26.sql
-- Alebo skopíruj a vlož do pgAdmin / DBeaver

-- POZNÁMKA: Ak projekt 26 má team_member_ids, môžeš nahradiť NULL v raci_accountable
-- a '[]' v raci_responsible/consulted/informed platnými ID členov tímu.

INSERT INTO tasks (
  project_id, sprint_id, epic_id, name, title, description, status, priority, type,
  story_points, due_date, completed, labels, complexity,
  pert_optimistic, pert_most_likely, pert_pessimistic, pert_expected,
  raci_responsible, raci_accountable, raci_consulted, raci_informed,
  start_date, end_date, dependencies, diagram_position_x, diagram_position_y,
  required_skills, estimated_hours, actual_hours, risk_level,
  parent_task_id, has_subtasks, subtask_ids, created_at, updated_at
) VALUES
(26, NULL, NULL, 'API Gateway Implementation', 'API Gateway Implementation', 'Implement API gateway for microservices', 'To Do', 'high', 'task', 8, NULL, false, '["backend","api"]', 5, 24, 40, 56, 40, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["API","Gateway","Kong"]', 40, 0, 'medium', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'User Authentication Module', 'User Authentication Module', 'OAuth2 + JWT authentication', 'To Do', 'high', 'feature', 13, NULL, false, '["auth","security"]', 6, 39, 65, 91, 65, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["OAuth2","JWT","Python"]', 65, 0, 'medium', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Database Migration Scripts', 'Database Migration Scripts', 'Alembic migrations for schema versioning', 'To Do', 'medium', 'task', 5, NULL, false, '["database","devops"]', 4, 15, 25, 35, 25, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["PostgreSQL","Alembic","SQL"]', 25, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Frontend Dashboard Redesign', 'Frontend Dashboard Redesign', 'Vue/Quasar dashboard with charts', 'To Do', 'high', 'feature', 13, NULL, false, '["frontend","ui"]', 6, 39, 65, 91, 65, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Vue","Quasar","Chart.js"]', 65, 0, 'medium', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Unit Tests Coverage', 'Unit Tests Coverage', 'Increase unit test coverage to 80%', 'To Do', 'medium', 'task', 5, NULL, false, '["testing","quality"]', 4, 15, 25, 35, 25, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["pytest","coverage"]', 25, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Logging & Monitoring Setup', 'Logging & Monitoring Setup', 'ELK stack or Prometheus/Grafana', 'To Do', 'medium', 'task', 8, NULL, false, '["devops","monitoring"]', 5, 24, 40, 56, 40, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Prometheus","Grafana","ELK"]', 40, 0, 'medium', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Email Notification Service', 'Email Notification Service', 'Async email sending with templates', 'To Do', 'medium', 'feature', 8, NULL, false, '["backend","notifications"]', 5, 24, 40, 56, 40, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Celery","SendGrid","Jinja2"]', 40, 0, 'medium', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Search Functionality', 'Search Functionality', 'Full-text search with Elasticsearch', 'To Do', 'high', 'feature', 13, NULL, false, '["search","backend"]', 6, 39, 65, 91, 65, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Elasticsearch","Python"]', 65, 0, 'medium', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'File Upload & Storage', 'File Upload & Storage', 'S3-compatible storage integration', 'To Do', 'medium', 'task', 5, NULL, false, '["storage","backend"]', 4, 15, 25, 35, 25, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["S3","MinIO","boto3"]', 25, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'API Rate Limiting', 'API Rate Limiting', 'Implement rate limiting middleware', 'To Do', 'low', 'task', 3, NULL, false, '["api","security"]', 3, 9, 15, 21, 15, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Redis","FastAPI"]', 15, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Admin Panel CRUD', 'Admin Panel CRUD', 'CRUD operations for admin interface', 'To Do', 'medium', 'feature', 8, NULL, false, '["admin","frontend"]', 5, 24, 40, 56, 40, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Vue","Quasar","REST"]', 40, 0, 'medium', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'WebSocket Real-time Updates', 'WebSocket Real-time Updates', 'Real-time notifications via WebSocket', 'To Do', 'high', 'feature', 8, NULL, false, '["realtime","websocket"]', 5, 24, 40, 56, 40, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["WebSocket","FastAPI","Vue"]', 40, 0, 'medium', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Export to PDF/Excel', 'Export to PDF/Excel', 'Report export functionality', 'To Do', 'medium', 'task', 5, NULL, false, '["export","reports"]', 4, 15, 25, 35, 25, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["ReportLab","openpyxl"]', 25, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Audit Trail Implementation', 'Audit Trail Implementation', 'Track all user actions for compliance', 'To Do', 'medium', 'task', 5, NULL, false, '["audit","compliance"]', 4, 15, 25, 35, 25, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["PostgreSQL","Python"]', 25, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Caching Layer', 'Caching Layer', 'Redis caching for frequent queries', 'To Do', 'medium', 'task', 5, NULL, false, '["performance","cache"]', 4, 15, 25, 35, 25, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Redis","Python"]', 25, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Mobile Responsive Design', 'Mobile Responsive Design', 'Ensure all views work on mobile', 'To Do', 'high', 'task', 8, NULL, false, '["frontend","responsive"]', 5, 24, 40, 56, 40, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["CSS","Quasar","Vue"]', 40, 0, 'medium', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Integration Tests', 'Integration Tests', 'E2E and API integration tests', 'To Do', 'medium', 'task', 8, NULL, false, '["testing","qa"]', 5, 24, 40, 56, 40, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["pytest","Playwright"]', 40, 0, 'medium', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Documentation Update', 'Documentation Update', 'API docs and user guide', 'To Do', 'low', 'task', 3, NULL, false, '["docs"]', 3, 9, 15, 21, 15, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["OpenAPI","MkDocs"]', 15, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Performance Optimization', 'Performance Optimization', 'Query optimization and lazy loading', 'To Do', 'high', 'task', 8, NULL, false, '["performance","optimization"]', 5, 24, 40, 56, 40, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["PostgreSQL","Python","Vue"]', 40, 0, 'medium', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Error Handling & Retry Logic', 'Error Handling & Retry Logic', 'Robust error handling across services', 'To Do', 'medium', 'task', 5, NULL, false, '["reliability","backend"]', 4, 15, 25, 35, 25, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Python","Celery"]', 25, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Role-based Access Control', 'Role-based Access Control', 'RBAC permissions system', 'To Do', 'high', 'feature', 8, NULL, false, '["security","auth"]', 5, 24, 40, 56, 40, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Python","JWT","Vue"]', 40, 0, 'medium', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Bulk Operations API', 'Bulk Operations API', 'Batch create/update/delete endpoints', 'To Do', 'medium', 'task', 5, NULL, false, '["api","backend"]', 4, 15, 25, 35, 25, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["FastAPI","PostgreSQL"]', 25, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Data Validation Layer', 'Data Validation Layer', 'Pydantic schemas and validation', 'To Do', 'medium', 'task', 5, NULL, false, '["validation","backend"]', 4, 15, 25, 35, 25, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Pydantic","FastAPI"]', 25, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Scheduled Jobs & Cron', 'Scheduled Jobs & Cron', 'Background job scheduling', 'To Do', 'medium', 'task', 5, NULL, false, '["devops","backend"]', 4, 15, 25, 35, 25, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Celery","Redis"]', 25, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Localization i18n', 'Localization i18n', 'Multi-language support', 'To Do', 'low', 'task', 5, NULL, false, '["frontend","i18n"]', 4, 15, 25, 35, 25, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Vue","vue-i18n"]', 25, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Dark Mode Theme', 'Dark Mode Theme', 'Dark/light theme toggle', 'To Do', 'low', 'task', 3, NULL, false, '["frontend","ui"]', 3, 9, 15, 21, 15, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Quasar","Vue"]', 15, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Keyboard Shortcuts', 'Keyboard Shortcuts', 'Accessibility keyboard navigation', 'To Do', 'low', 'task', 3, NULL, false, '["frontend","a11y"]', 3, 9, 15, 21, 15, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["Vue","Quasar"]', 15, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Health Check Endpoint', 'Health Check Endpoint', 'K8s/Docker health probes', 'To Do', 'low', 'task', 2, NULL, false, '["devops","api"]', 2, 6, 10, 14, 10, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["FastAPI","Docker"]', 10, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Config Management', 'Config Management', 'Environment-based configuration', 'To Do', 'medium', 'task', 3, NULL, false, '["devops","config"]', 3, 9, 15, 21, 15, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["pydantic-settings","env"]', 15, 0, 'low', NULL, false, NULL, NOW(), NOW()),
(26, NULL, NULL, 'Security Audit Fixes', 'Security Audit Fixes', 'Address security scan findings', 'To Do', 'high', 'task', 5, NULL, false, '["security","audit"]', 4, 15, 25, 35, 25, '[]', NULL, '[]', '[]', NULL, NULL, '[]', NULL, NULL, '["OWASP","Python"]', 25, 0, 'high', NULL, false, NULL, NOW(), NOW());

-- Aktualizácia total_story_points v projekte 26
-- Súčet story_points (30 taskov): 188
UPDATE projects
SET total_story_points = total_story_points + 188
WHERE id = 26;
